-- Oracle / DBeaver: fresh application schema only.
-- Based on the DDL supplied by the project owner.
-- Connect as the application owner before executing these statements.
-- User creation, storage settings and internal identity sequences are omitted.
-- Stop on the first error. Oracle DDL commits implicitly.
-- Identity options use parentheses; no separate CREATE SEQUENCE is required.

CREATE TABLE "MEMBER" (
    "MEMBER_NO"       NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "MEMBER_ID"       NVARCHAR2(20) NOT NULL,
    "MEMBER_PWD"      VARCHAR2(200) NOT NULL,
    "MEMBER_NAME"     NVARCHAR2(30) NOT NULL,
    "PHONE"          VARCHAR2(500) NOT NULL,
    "EMAIL"          VARCHAR2(500) NOT NULL,
    "MEMBER_IMG"     VARCHAR2(300),
    "ROLE"           VARCHAR2(10) DEFAULT 'ROLE_USER' NOT NULL,
    "CREATE_DATE"    DATE DEFAULT SYSDATE NOT NULL,
    "DEL_YN"         CHAR(1) DEFAULT 'N' NOT NULL,
    "MEMBER_IMG_PATH" VARCHAR2(300),
    "EMAIL_HASH"     VARCHAR2(64),
    "PHONE_HASH"     VARCHAR2(64),
    CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MEMBER_NO"),
    CONSTRAINT "UK_MEMBER_ID" UNIQUE ("MEMBER_ID")
);

CREATE INDEX "IX_MEMBER_EMAIL_HASH" ON "MEMBER" ("EMAIL_HASH");
CREATE INDEX "IX_MEMBER_PHONE_HASH" ON "MEMBER" ("PHONE_HASH");

COMMENT ON COLUMN "MEMBER"."DEL_YN" IS 'Y: 탈퇴, N: 정상';

CREATE TABLE "RECIPES" (
    "RECIPE_NO"        NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "MEMBER_NO"        NUMBER NOT NULL,
    "RECIPE_TITLE"     NVARCHAR2(50) NOT NULL,
    "RECIPE_INFO"      NVARCHAR2(1000) NOT NULL,
    "RECIPE_MAIN_IMG"  VARCHAR2(300) NOT NULL,
    "CREATE_DATE"      DATE DEFAULT SYSDATE NOT NULL,
    "DEL_YN"           CHAR(1) DEFAULT 'N' NOT NULL,
    "RECIPES_IMG_PATH" NVARCHAR2(300) NOT NULL,
    "COOKING_METHOD"   NVARCHAR2(20) NOT NULL,
    "RECIPE_TYPE"      NVARCHAR2(20) NOT NULL,
    "CALORIE"          NUMBER,
    "CARBOHYDRATE"     NUMBER,
    "PROTEIN"          NUMBER,
    "FAT"              NUMBER,
    "SODIUM"           NUMBER,
    "MAIN_MATERIAL"    NVARCHAR2(20),
    "VIEW_COUNT"       NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_RECIPES" PRIMARY KEY ("RECIPE_NO"),
    CONSTRAINT "FK_MEMBER_TO_RECIPES_1" FOREIGN KEY ("MEMBER_NO")
        REFERENCES "MEMBER" ("MEMBER_NO")
);

COMMENT ON COLUMN "RECIPES"."DEL_YN" IS 'Y: 삭제, N: 정상';

CREATE TABLE "DEVICE" (
    "DEVICE_NO"   NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "MEMBER_NO"   NUMBER NOT NULL,
    "CREATE_DATE" DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT "PK_DEVICE" PRIMARY KEY ("DEVICE_NO"),
    CONSTRAINT "UK_DEVICE_MEMBER" UNIQUE ("MEMBER_NO"),
    CONSTRAINT "FK_DEVICE_MEMBER" FOREIGN KEY ("MEMBER_NO")
        REFERENCES "MEMBER" ("MEMBER_NO")
);

CREATE TABLE "MATERIAL" (
    "MATERIAL_NO"   NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "RECIPE_NO"     NUMBER NOT NULL,
    "MATERIAL_NAME" NVARCHAR2(30) NOT NULL,
    "AMOUNT"        NVARCHAR2(45) NOT NULL,
    CONSTRAINT "PK_MATERIAL" PRIMARY KEY ("MATERIAL_NO"),
    CONSTRAINT "FK_RECIPES_TO_MATERIAL_1" FOREIGN KEY ("RECIPE_NO")
        REFERENCES "RECIPES" ("RECIPE_NO")
);

CREATE TABLE "MEMBER_ALLERGY" (
    "MEMBER_ALLERGY_NO" NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "MEMBER_NO"         NUMBER NOT NULL,
    "MATERIAL_NAME"     NVARCHAR2(30) NOT NULL,
    CONSTRAINT "PK_MEMBER_ALLERGY" PRIMARY KEY ("MEMBER_ALLERGY_NO"),
    CONSTRAINT "UK_MEMBER_ALLERGY" UNIQUE ("MEMBER_NO", "MATERIAL_NAME"),
    CONSTRAINT "FK_MEMBER_TO_MEMBER_ALLERGY_1" FOREIGN KEY ("MEMBER_NO")
        REFERENCES "MEMBER" ("MEMBER_NO")
);

CREATE TABLE "RECIPE_STEPS" (
    "STEP_NO"       NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "RECIPE_NO"     NUMBER NOT NULL,
    "STEP_INFO"    VARCHAR2(2000) NOT NULL,
    "STEP_IMG"     VARCHAR2(300),
    "STEP_ORDER"   NUMBER NOT NULL,
    "STEP_IMG_PATH" NVARCHAR2(300),
    CONSTRAINT "PK_RECIPE_STEPS" PRIMARY KEY ("STEP_NO"),
    CONSTRAINT "UK_RECIPE_STEPS_ORDER" UNIQUE ("RECIPE_NO", "STEP_ORDER"),
    CONSTRAINT "FK_RECIPES_TO_RECIPE_STEPS_1" FOREIGN KEY ("RECIPE_NO")
        REFERENCES "RECIPES" ("RECIPE_NO")
);

CREATE TABLE "STEP_LOG" (
    "STEP_LOG_NO" NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "DEVICE_NO"   NUMBER NOT NULL,
    "TODAY_STEPS" NUMBER NOT NULL,
    "CREATE_DATE" DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT "PK_STEP_LOG" PRIMARY KEY ("STEP_LOG_NO"),
    CONSTRAINT "FK_STEP_LOG_DEVICE" FOREIGN KEY ("DEVICE_NO")
        REFERENCES "DEVICE" ("DEVICE_NO")
);

CREATE INDEX "IX_STEP_LOG_DEVICE_DATE" ON "STEP_LOG" ("DEVICE_NO", "CREATE_DATE");

CREATE TABLE "TOKEN" (
    "TOKEN_NO"   NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "MEMBER_NO"  NUMBER NOT NULL,
    "TOKEN"      VARCHAR2(300) NOT NULL,
    "EXPIRATION" NUMBER NOT NULL,
    CONSTRAINT "PK_TOKEN" PRIMARY KEY ("TOKEN_NO"),
    CONSTRAINT "UK_TOKEN" UNIQUE ("TOKEN"),
    CONSTRAINT "FK_MEMBER_TO_TOKEN_1" FOREIGN KEY ("MEMBER_NO")
        REFERENCES "MEMBER" ("MEMBER_NO")
);

CREATE TABLE "BOOKMARK" (
    "MEMBER_NO"   NUMBER NOT NULL,
    "RECIPE_NO"   NUMBER NOT NULL,
    "CREATE_DATE" DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT "PK_BOOKMARK" PRIMARY KEY ("MEMBER_NO", "RECIPE_NO"),
    CONSTRAINT "FK_MEMBER_TO_BOOKMARK_1" FOREIGN KEY ("MEMBER_NO")
        REFERENCES "MEMBER" ("MEMBER_NO"),
    CONSTRAINT "FK_RECIPES_TO_BOOKMARK_1" FOREIGN KEY ("RECIPE_NO")
        REFERENCES "RECIPES" ("RECIPE_NO")
);
