-- Oracle / DBeaver: run once after schema.sql in a development database.
-- Login: admin / admin1234. The stored password is BCrypt, not plaintext.
-- Use manual commit and stop on the first SQL error.
-- On error, stop the script and ROLLBACK instead of running the final COMMIT.
-- An existing admin account is not overwritten; the first INSERT will fail.
-- Identity PKs are omitted. FK values are resolved by subqueries.
-- Email/phone are dummy plaintext values for the app's legacy-data fallback.
-- Their keyed HMAC values are NULL; this account does not exercise deduplication.
-- Image URLs are placeholders, not actual images or S3 objects.

-- 1. Temporary administrator
INSERT INTO MEMBER (
    MEMBER_ID, MEMBER_PWD, MEMBER_NAME, PHONE, EMAIL,
    ROLE, EMAIL_HASH, PHONE_HASH
) VALUES (
    N'admin',
    '$2a$10$UsYyk1uDxU6bxTKBF91TSeiOhX.vIR57l16DVUGda2H2anxlZfMNu',
    N'임시관리자', '01000000000', 'admin@example.com',
    'ROLE_ADMIN', NULL, NULL
);

-- 2. Allergies
INSERT INTO MEMBER_ALLERGY (MEMBER_NO, MATERIAL_NAME)
VALUES ((SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N'), N'땅콩');

INSERT INTO MEMBER_ALLERGY (MEMBER_NO, MATERIAL_NAME)
VALUES ((SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N'), N'우유');

-- Recipe 1: [샘플] 닭고기 덮밥
INSERT INTO RECIPES (
    MEMBER_NO, RECIPE_TITLE, RECIPE_INFO, RECIPE_MAIN_IMG,
    RECIPES_IMG_PATH, COOKING_METHOD, RECIPE_TYPE,
    CALORIE, MAIN_MATERIAL, VIEW_COUNT
) VALUES (
    (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N'),
    N'[샘플] 닭고기 덮밥', N'개발용 예시 데이터입니다. 재료와 영양 수치는 테스트용입니다.',
    'sample-placeholder.jpg', N'https://example.com/allergy-out/sample-placeholder.jpg',
    N'볶기', N'밥', 650, N'닭고기', 20
);

INSERT INTO MATERIAL (RECIPE_NO, MATERIAL_NAME, AMOUNT)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 닭고기 덮밥'), N'닭고기', N'100g');

INSERT INTO MATERIAL (RECIPE_NO, MATERIAL_NAME, AMOUNT)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 닭고기 덮밥'), N'쌀', N'100g');

INSERT INTO RECIPE_STEPS (RECIPE_NO, STEP_INFO, STEP_ORDER)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 닭고기 덮밥'), N'재료를 준비합니다. (테스트용 단계)', 1);

INSERT INTO RECIPE_STEPS (RECIPE_NO, STEP_INFO, STEP_ORDER)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 닭고기 덮밥'), N'준비한 재료를 조리하고 그릇에 담습니다. (테스트용 단계)', 2);

-- Recipe 2: [샘플] 두부 채소밥
INSERT INTO RECIPES (
    MEMBER_NO, RECIPE_TITLE, RECIPE_INFO, RECIPE_MAIN_IMG,
    RECIPES_IMG_PATH, COOKING_METHOD, RECIPE_TYPE,
    CALORIE, MAIN_MATERIAL, VIEW_COUNT
) VALUES (
    (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N'),
    N'[샘플] 두부 채소밥', N'개발용 예시 데이터입니다. 재료와 영양 수치는 테스트용입니다.',
    'sample-placeholder.jpg', N'https://example.com/allergy-out/sample-placeholder.jpg',
    N'볶기', N'밥', 700, N'두부', 30
);

INSERT INTO MATERIAL (RECIPE_NO, MATERIAL_NAME, AMOUNT)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 두부 채소밥'), N'두부', N'100g');

INSERT INTO MATERIAL (RECIPE_NO, MATERIAL_NAME, AMOUNT)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 두부 채소밥'), N'쌀', N'100g');

INSERT INTO RECIPE_STEPS (RECIPE_NO, STEP_INFO, STEP_ORDER)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 두부 채소밥'), N'재료를 준비합니다. (테스트용 단계)', 1);

INSERT INTO RECIPE_STEPS (RECIPE_NO, STEP_INFO, STEP_ORDER)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 두부 채소밥'), N'준비한 재료를 조리하고 그릇에 담습니다. (테스트용 단계)', 2);

-- Recipe 3: [샘플] 버섯 볶음밥
INSERT INTO RECIPES (
    MEMBER_NO, RECIPE_TITLE, RECIPE_INFO, RECIPE_MAIN_IMG,
    RECIPES_IMG_PATH, COOKING_METHOD, RECIPE_TYPE,
    CALORIE, MAIN_MATERIAL, VIEW_COUNT
) VALUES (
    (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N'),
    N'[샘플] 버섯 볶음밥', N'개발용 예시 데이터입니다. 재료와 영양 수치는 테스트용입니다.',
    'sample-placeholder.jpg', N'https://example.com/allergy-out/sample-placeholder.jpg',
    N'볶기', N'밥', 750, N'버섯', 10
);

INSERT INTO MATERIAL (RECIPE_NO, MATERIAL_NAME, AMOUNT)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 버섯 볶음밥'), N'버섯', N'100g');

INSERT INTO MATERIAL (RECIPE_NO, MATERIAL_NAME, AMOUNT)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 버섯 볶음밥'), N'쌀', N'100g');

INSERT INTO RECIPE_STEPS (RECIPE_NO, STEP_INFO, STEP_ORDER)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 버섯 볶음밥'), N'재료를 준비합니다. (테스트용 단계)', 1);

INSERT INTO RECIPE_STEPS (RECIPE_NO, STEP_INFO, STEP_ORDER)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 버섯 볶음밥'), N'준비한 재료를 조리하고 그릇에 담습니다. (테스트용 단계)', 2);

-- Recipe 4: [샘플] 땅콩버터 비빔면
INSERT INTO RECIPES (
    MEMBER_NO, RECIPE_TITLE, RECIPE_INFO, RECIPE_MAIN_IMG,
    RECIPES_IMG_PATH, COOKING_METHOD, RECIPE_TYPE,
    CALORIE, MAIN_MATERIAL, VIEW_COUNT
) VALUES (
    (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N'),
    N'[샘플] 땅콩버터 비빔면', N'개발용 예시 데이터입니다. 재료와 영양 수치는 테스트용입니다.',
    'sample-placeholder.jpg', N'https://example.com/allergy-out/sample-placeholder.jpg',
    N'기타', N'일품', 690, N'땅콩버터', 40
);

INSERT INTO MATERIAL (RECIPE_NO, MATERIAL_NAME, AMOUNT)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 땅콩버터 비빔면'), N'땅콩버터', N'100g');

INSERT INTO MATERIAL (RECIPE_NO, MATERIAL_NAME, AMOUNT)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 땅콩버터 비빔면'), N'면', N'100g');

INSERT INTO RECIPE_STEPS (RECIPE_NO, STEP_INFO, STEP_ORDER)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 땅콩버터 비빔면'), N'재료를 준비합니다. (테스트용 단계)', 1);

INSERT INTO RECIPE_STEPS (RECIPE_NO, STEP_INFO, STEP_ORDER)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 땅콩버터 비빔면'), N'준비한 재료를 조리하고 그릇에 담습니다. (테스트용 단계)', 2);

-- Recipe 5: [샘플] 우유 감자수프
INSERT INTO RECIPES (
    MEMBER_NO, RECIPE_TITLE, RECIPE_INFO, RECIPE_MAIN_IMG,
    RECIPES_IMG_PATH, COOKING_METHOD, RECIPE_TYPE,
    CALORIE, MAIN_MATERIAL, VIEW_COUNT
) VALUES (
    (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N'),
    N'[샘플] 우유 감자수프', N'개발용 예시 데이터입니다. 재료와 영양 수치는 테스트용입니다.',
    'sample-placeholder.jpg', N'https://example.com/allergy-out/sample-placeholder.jpg',
    N'끓이기', N'국' || NCHR(38) || N'찌개', 710, N'우유', 50
);

INSERT INTO MATERIAL (RECIPE_NO, MATERIAL_NAME, AMOUNT)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 우유 감자수프'), N'우유', N'100g');

INSERT INTO MATERIAL (RECIPE_NO, MATERIAL_NAME, AMOUNT)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 우유 감자수프'), N'감자', N'100g');

INSERT INTO RECIPE_STEPS (RECIPE_NO, STEP_INFO, STEP_ORDER)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 우유 감자수프'), N'재료를 준비합니다. (테스트용 단계)', 1);

INSERT INTO RECIPE_STEPS (RECIPE_NO, STEP_INFO, STEP_ORDER)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 우유 감자수프'), N'준비한 재료를 조리하고 그릇에 담습니다. (테스트용 단계)', 2);

-- Recipe 6: [샘플] 과일 컵
INSERT INTO RECIPES (
    MEMBER_NO, RECIPE_TITLE, RECIPE_INFO, RECIPE_MAIN_IMG,
    RECIPES_IMG_PATH, COOKING_METHOD, RECIPE_TYPE,
    CALORIE, MAIN_MATERIAL, VIEW_COUNT
) VALUES (
    (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N'),
    N'[샘플] 과일 컵', N'개발용 예시 데이터입니다. 재료와 영양 수치는 테스트용입니다.',
    'sample-placeholder.jpg', N'https://example.com/allergy-out/sample-placeholder.jpg',
    N'기타', N'후식', NULL, N'사과', 0
);

INSERT INTO MATERIAL (RECIPE_NO, MATERIAL_NAME, AMOUNT)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 과일 컵'), N'사과', N'100g');

INSERT INTO MATERIAL (RECIPE_NO, MATERIAL_NAME, AMOUNT)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 과일 컵'), N'바나나', N'100g');

INSERT INTO RECIPE_STEPS (RECIPE_NO, STEP_INFO, STEP_ORDER)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 과일 컵'), N'재료를 준비합니다. (테스트용 단계)', 1);

INSERT INTO RECIPE_STEPS (RECIPE_NO, STEP_INFO, STEP_ORDER)
VALUES ((SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 과일 컵'), N'준비한 재료를 조리하고 그릇에 담습니다. (테스트용 단계)', 2);

-- 3. Bookmarks
INSERT INTO BOOKMARK (MEMBER_NO, RECIPE_NO)
VALUES ((SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N'), (SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 닭고기 덮밥'));

INSERT INTO BOOKMARK (MEMBER_NO, RECIPE_NO)
VALUES ((SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N'), (SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N') AND RECIPE_TITLE = N'[샘플] 두부 채소밥'));

-- 4. Device
INSERT INTO DEVICE (MEMBER_NO)
VALUES ((SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N'));

-- 5. Previous six days and two cumulative reports today
INSERT INTO STEP_LOG (DEVICE_NO, TODAY_STEPS, CREATE_DATE)
VALUES ((SELECT DEVICE_NO FROM DEVICE WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N')), 7000, TRUNC(SYSDATE) - 6 + 0.5);

INSERT INTO STEP_LOG (DEVICE_NO, TODAY_STEPS, CREATE_DATE)
VALUES ((SELECT DEVICE_NO FROM DEVICE WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N')), 6500, TRUNC(SYSDATE) - 5 + 0.5);

INSERT INTO STEP_LOG (DEVICE_NO, TODAY_STEPS, CREATE_DATE)
VALUES ((SELECT DEVICE_NO FROM DEVICE WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N')), 6000, TRUNC(SYSDATE) - 4 + 0.5);

INSERT INTO STEP_LOG (DEVICE_NO, TODAY_STEPS, CREATE_DATE)
VALUES ((SELECT DEVICE_NO FROM DEVICE WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N')), 5500, TRUNC(SYSDATE) - 3 + 0.5);

INSERT INTO STEP_LOG (DEVICE_NO, TODAY_STEPS, CREATE_DATE)
VALUES ((SELECT DEVICE_NO FROM DEVICE WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N')), 5000, TRUNC(SYSDATE) - 2 + 0.5);

INSERT INTO STEP_LOG (DEVICE_NO, TODAY_STEPS, CREATE_DATE)
VALUES ((SELECT DEVICE_NO FROM DEVICE WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N')), 4500, TRUNC(SYSDATE) - 1 + 0.5);

INSERT INTO STEP_LOG (DEVICE_NO, TODAY_STEPS, CREATE_DATE)
VALUES ((SELECT DEVICE_NO FROM DEVICE WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N')), 1000, TRUNC(SYSDATE));

INSERT INTO STEP_LOG (DEVICE_NO, TODAY_STEPS, CREATE_DATE)
VALUES ((SELECT DEVICE_NO FROM DEVICE WHERE MEMBER_NO = (SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N')), 3600, SYSDATE);

COMMIT;
