-- Read-only checks immediately after seed.sql, before editing sample data.
SELECT MEMBER_NO, MEMBER_ID, MEMBER_NAME, ROLE, DEL_YN
  FROM MEMBER WHERE MEMBER_ID = N'admin';

-- Expected counts: 2 allergies, 6 recipes, 12 materials, 12 steps, 2 bookmarks, 1 device, 8 logs.
WITH demo AS (
    SELECT MEMBER_NO FROM MEMBER WHERE MEMBER_ID = N'admin' AND DEL_YN = 'N'
)
SELECT 'MEMBER_ALLERGY' AS ENTITY, COUNT(*) AS ROW_COUNT
  FROM MEMBER_ALLERGY WHERE MEMBER_NO IN (SELECT MEMBER_NO FROM demo)
UNION ALL
SELECT 'RECIPES', COUNT(*) FROM RECIPES WHERE MEMBER_NO IN (SELECT MEMBER_NO FROM demo)
UNION ALL
SELECT 'MATERIAL', COUNT(*) FROM MATERIAL
 WHERE RECIPE_NO IN (SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO IN (SELECT MEMBER_NO FROM demo))
UNION ALL
SELECT 'RECIPE_STEPS', COUNT(*) FROM RECIPE_STEPS
 WHERE RECIPE_NO IN (SELECT RECIPE_NO FROM RECIPES WHERE MEMBER_NO IN (SELECT MEMBER_NO FROM demo))
UNION ALL
SELECT 'BOOKMARK', COUNT(*) FROM BOOKMARK WHERE MEMBER_NO IN (SELECT MEMBER_NO FROM demo)
UNION ALL
SELECT 'DEVICE', COUNT(*) FROM DEVICE WHERE MEMBER_NO IN (SELECT MEMBER_NO FROM demo)
UNION ALL
SELECT 'STEP_LOG', COUNT(*) FROM STEP_LOG
 WHERE DEVICE_NO IN (SELECT DEVICE_NO FROM DEVICE WHERE MEMBER_NO IN (SELECT MEMBER_NO FROM demo));

-- Expected allergy-filtered recipe count: 4.
SELECT r.RECIPE_TITLE, r.CALORIE
  FROM RECIPES r
 WHERE r.DEL_YN = 'N'
   AND r.RECIPE_NO NOT IN (
       SELECT mat.RECIPE_NO
         FROM MATERIAL mat
         JOIN MEMBER_ALLERGY ma ON mat.MATERIAL_NAME LIKE '%' || ma.MATERIAL_NAME || '%'
         JOIN MEMBER m ON m.MEMBER_NO = ma.MEMBER_NO
        WHERE m.MEMBER_ID = N'admin' AND m.DEL_YN = 'N'
   )
 ORDER BY r.RECIPE_NO;

-- Expected recommended calories: 700, 650, 750 (in this order).
SELECT r.RECIPE_TITLE, r.CALORIE
  FROM RECIPES r
 WHERE r.DEL_YN = 'N'
   AND r.CALORIE IS NOT NULL
   AND r.RECIPE_NO NOT IN (
       SELECT mat.RECIPE_NO
         FROM MATERIAL mat
         JOIN MEMBER_ALLERGY ma ON mat.MATERIAL_NAME LIKE '%' || ma.MATERIAL_NAME || '%'
         JOIN MEMBER m ON m.MEMBER_NO = ma.MEMBER_NO
        WHERE m.MEMBER_ID = N'admin' AND m.DEL_YN = 'N'
   )
 ORDER BY ABS(r.CALORIE - 700), r.VIEW_COUNT DESC, r.CREATE_DATE, r.RECIPE_NO
 FETCH FIRST 3 ROWS ONLY;

-- Expected seven days, with 3600 steps today.
SELECT TRUNC(s.CREATE_DATE) AS STEP_DATE, MAX(s.TODAY_STEPS) AS STEPS
  FROM STEP_LOG s
  JOIN DEVICE d ON d.DEVICE_NO = s.DEVICE_NO
  JOIN MEMBER m ON m.MEMBER_NO = d.MEMBER_NO
 WHERE m.MEMBER_ID = N'admin' AND m.DEL_YN = 'N'
   AND s.CREATE_DATE >= TRUNC(SYSDATE) - 6
 GROUP BY TRUNC(s.CREATE_DATE)
 ORDER BY STEP_DATE;
